# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# Site info
name: 'Hemanth Kumar Narra'
title: 'My Personal website'
tagline: 'Introvert'  # it will display as the sub-title
description: 'Human | CA & CMA student | Investor | Python'
url: 'https://hemanthnarra.in'

# SEO > author meta
author: Hemanth Kumar Narra
# -------------------------------------------------------------------------
# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Kolkata
# -------------------------------------------------------------------------
markdown: kramdown
permalink: /blog/:title
plugins:
  - jekyll-seo-tag
  - jemoji
